- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf
    ~/.nvim: nvim
    ~/.nvimrc: nvimrc
    ~/.bashrc: bashrc
    ~/.bash_aliases: bash_aliases
    ~/.gitconfig: gitconfig

- shell:
  - [git submodule update --init --recursive, Instaling submodules]
  - [./fonts/install.sh]
