- clean: ['~']

- shell:
  - [git submodule update --init --recursive, Instaling submodules]
  - [./fonts/install.sh]
  - [./mkenvfile]
  - [rm ~/.bashrc]
  - [rm ~/.bash_aliases]

- link:
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux
    ~/.config/nvim: nvim
    ~/.bashrc: bashrc
    ~/.bash_aliases: bash_aliases
    ~/.gitconfig: gitconfig
    ~/.environment-variables: environment-variables
    ~/.agignore: agignore
    ~/.nvmrc: nvmrc
